const sitemapAlternates = require("../_includes/sitemap/alternate");

module.exports = class {
    data() {
        return {
            layout: 'layout.11ty.js',
            pageTitle: 'Informativa Privacy',
            author: 'Nexxo Cross Platform S.r.l.',
            pageDescription: 'Questo Sito Web raccoglie alcuni Dati Personali dei propri Utenti.',
            eleventyNavigation: {
                key: 'informativa-privacy',
                title: 'Informativa Privacy',
            },
            isWhiteFooter: true,
            canonicalPageRelativeUrl: 'it/informativa-privacy/',
            ogImageRelativeUrl: 'assets/img/landing/software-company/nexxo-varese-hero.jpg',
            sitemap: {
                links: sitemapAlternates.privacyPolicy
            }
        }
    }

    async render(data) {
        return `
        <!-- Breadcrumb -->
        <nav class="container py-4 my-lg-3" aria-label="breadcrumb">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
              <a href="${this.i18n('pagesUrl.homepage')}"><i class="bx bx-home-alt fs-lg me-1"></i>${this.i18n('pagesUrl.homepage.linkName')}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">${this.i18n('pagesUrl.privacyPolicy.linkName')}</li>
          </ol>
        </nav>

        <section class="container">
        <h1>INFORMATIVA PRIVACY</h1>
        <h2>INFORMATIVA ESTESA AI SENSI DEGLI ARTT. 12, 13 E, OCCORRENDO, 14 DEL GDPR – REGOLAMENTO (UE) 2016/679 RELATIVO ALLA PROTEZIONE DELLE PERSONE FISICHE, CON RIGUARDO AL TRATTAMENTO DEI DATI PERSONALI (DI SEGUITO IL GDPR)</h2>
            <p>Il titolare del trattamento riporta, di seguito, l’Informativa ai sensi degli artt. 12, 13 e, occorrendo, 14 del GDPR relativa al trattamento dei dati personali forniti dal Cliente/interessato tramite la compilazione e sottoscrizione del Contratto per acquistare i prodotti/servizi offerti in vendita dal titolare del trattamento stesso, caricando spontaneamente in questo sito web dati personali (in particolare attraverso la compilazione di form) o semplicemente navigando in esso.</p>
        <h3>1. TITOLARE DEL TRATTAMENTO E DATI DI CONTATTO</h3>
            <p>Titolare del trattamento è Nexxo Cross Platform S.r.l. – Via Ernesto Cairoli 5 21100 Varese (VA), Partita Iva 03799860121, Tel. 0332 1580 443, email: info@nexxoxp.com</p>
        <h3>2. PRINCIPI APPLICABILI AL TRATTAMENTO</h3>
            <p>Conformemente a quanto prescritto dal GDPR, il titolare del trattamento si adopera costantemente affinché i dati personali siano:</p>
        <ol type="a">
            <li>trattati in modo lecito, corretto e trasparente;</li>
            <li>raccolti per finalità determinate, esplicite e legittime, e successivamente trattati in modo che non sia incompatibile con tali finalità;</li>
            <li>adeguati, pertinenti e limitati a quanto necessario rispetto alle finalità per le quali sono trattati;</li>
            <li>esatti e, se necessario, aggiornati;</li>
            <li>conservati per un arco di tempo non superiore al conseguimento delle finalità per le quali sono trattati;</li>
            <li>trattati, mediante misure tecniche e organizzative adeguate, in maniera da garantirne la sicurezza;</li>
            <li>trattati, qualora in forza di consenso, per decisione liberamente assunta dal Cliente/interessato, sulla base di richiesta presentata in modo chiaramente distinguibile dal resto, in forma comprensibile e facilmente accessibile, utilizzando un linguaggio semplice e chiaro.</li>
        </ol>
            <p>Il titolare del trattamento adotta misure tecniche e organizzative adeguate al fine di assicurare la protezione dei dati personali fin dalla progettazione e per garantire che siano trattati, per impostazione predefinita, solo i dati necessari per ogni specifica finalità di trattamento.</p>
            <p>Il titolare del trattamento raccoglie e tiene nella massima considerazione indicazioni, osservazioni e pareri del Cliente/interessato trasmessi ai recapiti sopra riportati, al fine di implementare un sistema di privacy management dinamico che assicuri effettiva protezione delle persone, con riguardo al trattamento dei loro dati.</p>
        <h3>3. MODALITÀ DEL TRATTAMENTO DEI DATI PERSONALI</h3>
            <p>Il trattamento dei dati personali viene effettuato manualmente e con strumenti elettronici, con logiche strettamente correlate alle finalità di seguito indicate e, comunque, in modo da garantire la sicurezza e la riservatezza dei dati stessi.</p>
        <h3>4. FINALITÀ DEL TRATTAMENTO DEI DATI PERSONALI</h3>
        <h4>(4a) Finalità per cui il trattamento dei dati è necessario</h4>
            <p>I dati personali forniti dal Cliente/interessato sono principalmente trattati per l’esecuzione del Contratto e la gestione del credito e, più in generale, del rapporto nascente dal Contratto stesso.</p>
            <p>Oltre a questa possibilità, i dati possono essere trattati per la selezione di nuovo personale, per la di distribuzione dei prodotti / servizi, gestione dei fornitori ed altri casi derivanti dalla richiesta del cliente / interessato o di normale amministrazione aziendale.</p>
            <p>Il conferimento dei dati nel Contratto o in seguito, nel corso del rapporto contrattuale, per le finalità di trattamento in parola è obbligatorio; pertanto, il mancato, parziale o inesatto conferimento di tali dati rende impossibile la stipula e/o l’esecuzione del Contratto e, per il Cliente/interessato, usufruire dei prodotti/servizi offerti dal titolare del trattamento, potenzialmente esponendo il Cliente/interessato medesimo a responsabilità per inadempimento contrattuale.</p>
            <p>I dati personali forniti dal Cliente/interessato possono, altresì, formare oggetto di trattamento se ciò è necessario per adempiere un obbligo legale al quale è soggetto il titolare del trattamento, per la salvaguardia degli interessi vitali del Cliente/interessato o di un’altra persona fisica, per l’esecuzione di un compito di interesse pubblico o connesso all’esercizio di pubblici poteri di cui è investito il titolare del trattamento, ovvero per il perseguimento del legittimo interesse del titolare del trattamento stesso o di terzi, a condizione che non prevalgano gli interessi o i diritti e le libertà fondamentali del Cliente/interessato; anche in questi casi, il conferimento dei dati è obbligatorio e, pertanto, la mancata, parziale o inesatta comunicazione dei dati può esporre il Cliente/interessato a eventuali responsabilità e sanzioni previste dall’Ordinamento giuridico.</p>
        <h4>(4b) Ulteriori finalità del trattamento a seguito di specifico ed espresso consenso del Cliente/interessato</h4>
            <p>Oltre che per le finalità di trattamento di cui sopra, i dati personali conferiti/acquisiti possono essere trattati, previo consenso del Cliente/interessato, da esprimere selezionando la casell "Presta il consenso" sul Contratto o sul Sito (o utilizzando altre applicazioni social o web del titolare del trattamento), anche per lo svolgimento di indagini di mercato e per effettuare comunicazioni commerciali e promozionali, tramite telefono (anche utilizzando il numero di cellulare fornito) e sistemi automatizzati di contatto (e-mail, sms, mms, fax, ecc.), su prodotti/servizi del titolare del trattamento o di società del Gruppo cui il titolare del trattamento eventualmente appartiene.</p>
            <p>Il consenso per le finalità di trattamento di cui al presente punto (4b) è facoltativo; pertanto, a seguito di eventuale diniego, i dati saranno trattati per le sole finalità indicate al precedente punto (4a), salvo quanto di seguito specificato con riferimento agli interessi legittimi del titolare del trattamento o di terzi.</p>
        <h3>5. CATEGORIE DI DATI PERSONALI TRATTATI</h3>
            <p>Il titolare del trattamento tratta principalmente dati identificativi/di contatto (nome, cognome, indirizzi, tipo e numero di documenti di riconoscimento, numeri di telefono, indirizzi e-mail, di natura fiscale/di fatturazione, salvo altri) e, qualora siano previste transazioni commerciali, dati finanziari (di natura bancaria, in particolare identificativi di conti correnti, numeri di carte di credito, salvo altri connessi alle predette transazioni commerciali).</p>
            <p>Il trattamento che il titolare del trattamento effettua, tanto per l’esecuzione del Contratto quanto in forza di espresso consenso del Cliente/interessato, non riguarda, generalmente, categorie particolari di dati personali, conosciuti come sensibili (che rivelino l’origine razziale o etnica, le opinioni politiche, le convinzioni religiose, lo stato di salute o l’orientamento sessuale, ecc.), né dati genetici e biometrici o dati cosiddetti giudiziari (relativi a condanne penali e reati).</p>
            <p>Tuttavia, non può escludersi che il titolare del trattamento, al fine di eseguire le obbligazioni discendenti dal Contratto, debba conservare e/o abbia la necessità di trattare dati sensibili, genetici e biometrici o giudiziari, del Cliente/interessato o di terzi, di cui il Cliente/interessato disponga in qualità di titolare del trattamento; nell’ipotesi in parola, il trattamento ad opera del titolare del trattamento avviene in forza, alle condizioni e nei limiti di cui alla nomina dello stesso titolare del trattamento a responsabile del trattamento, ad opera del Cliente/interessato.</p>
            <p>Il titolare del trattamento tratta, in qualità di titolare del trattamento con riferimento al Sito, e, potenzialmente, quale responsabile del trattamento a ciò incaricato (nei termini di cui sopra) dal Cliente/interessato, anche i cosiddetti dati di navigazione. I sistemi informatici e le procedure software preposte al funzionamento dei siti internet acquisiscono, nel corso del loro normale esercizio, alcuni dati personali, la cui trasmissione è implicita nell’uso di protocolli di comunicazione di internet. Si tratta di informazioni che non sono raccolte per essere associate a soggetti identificati, ma che, per la loro stessa natura, potrebbero permettere di identificare l’interessato. In questa categoria di informazioni rientrano dati di geolocalizzazione, indirizzi IP, tipo di browser, sistema operativo, nome di dominio e indirizzi di siti web dai quali è stato effettuato l’accesso o l’uscita, informazioni sulle pagine visitate dagli utenti all’interno del sito, orario d’accesso, permanenza sulla singola pagina, analisi di percorso interno ed altri parametri relativi al sistema operativo e all’ambiente informatico dell’utente. Si tratta, dunque, di informazioni che, per loro stessa natura, consentono, attraverso elaborazioni ed associazioni anche con dati detenuti da terzi, di identificare gli utenti.</p>
            <p>Sul Sito può, poi, essere fatto uso di cookies, sia di sessione (che non vengono memorizzati sul computer dell’interessato e svaniscono con la chiusura del browser) che persistenti, per la trasmissione di informazioni di carattere personale, ovvero comunque di sistemi per il tracciamento degli interessati.</p>
        <h3>6. FONTE DEI DATI PERSONALI</h3>
            <p>I dati personali che il titolare del trattamento tratta sono raccolti direttamente dal titolare del trattamento stesso presso il Cliente/interessato al momento della, e durante la, navigazione di questo sul Sito (o utilizzando altre applicazioni social o web del titolare del trattamento), ovvero, anche a mezzo dei propri commerciali, in occasione della, o successivamente alla, sottoscrizione del Contratto, in fase di esecuzione del medesimo, ovvero da fonti pubbliche.</p>
            <p>Come precisato sopra, il titolare del trattamento, quale responsabile del trattamento a ciò incaricato, al fine di eseguire le obbligazioni discendenti dal Contratto, può conservare e/o trattare dati, in particolare di navigazione, potenzialmente anche sensibili, genetici e biometrici o giudiziari, di terzi, di cui il Cliente/interessato disponga in qualità di titolare del trattamento, acquisiti, previo consenso di detti terzi, al momento della, e durante la, navigazione dei medesimi terzi sul Sito (o utilizzando altre applicazioni social o web riferibili al titolare del trattamento).</p>
        <h3>7. INTERESSI LEGITTIMI</h3>
            <p>I legittimi interessi del titolare del trattamento o di terzi possono costituire valida base giuridica del trattamento, a condizione che non prevalgano gli interessi o i diritti e le libertà fondamentali dell’interessato. In generale, possono sussistere tali legittimi interessi quando esiste una relazione pertinente e appropriata tra titolare del trattamento e interessato, ad esempio quando l’interessato è un cliente del titolare. Costituisce, in particolare, legittimo interesse del titolare del trattamento trattare dati personali del Cliente/interessato: a fini di prevenzione delle frodi, per finalità di marketing diretto, per assicurare la libera circolazione dei medesimi dati all’interno del Gruppo imprenditoriale cui il titolare del trattamento eventualmente appartiene, ovvero relativi al traffico, al fine di garantire la sicurezza delle reti e dell’informazione, vale a dire la capacità di una rete o di un sistema di resistere a eventi imprevisti o ad atti illeciti che possano compromettere la disponibilità, l’autenticità, l’integrità e la riservatezza dei dati.</p>
        <h3>8. CIRCOLAZIONE DEI DATI PERSONALI</h3>
        <h4>(8a) Comunicazione dei dati personali – categorie di destinatari</h4>
            <p>Oltre che dai dipendenti e collaboratori a vario titolo del titolare del trattamento (che sono dal titolare del trattamento stesso autorizzati al trattamento in forza di adeguate istruzioni operative scritte, al fine di poter garantire la riservatezza e la sicurezza dei dati), alcune operazioni di trattamento possono essere effettuate anche da soggetti terzi, ai quali il titolare del trattamento affida talune attività, o parte di esse, funzionali alle finalità di cui al punto (4a), dunque tanto in esecuzione di obblighi contrattuali quanto legali, tra cui meritano menzione, a titolo comunque, inevitabilmente, non esaustivo: partners commerciali e/o tecnici; società che prestano servizi bancari e finanziari; società che svolgono servizi di archiviazione di documenti; società di recupero crediti; società di revisione contabile e di certificazione dei bilanci; società di rating; soggetti che svolgono, a favore del titolare del trattamento, attività di assistenza e consulenza professionale; società che effettuano attività di customer care; società di factoring, di cartolarizzazione dei crediti o ad altro titolo cessionarie dei crediti; società del Gruppo cui il titolare del trattamento eventualmente appartiene; soggetti che forniscono informazioni commerciali; società di servizi informatici. I soggetti appartenenti alle predette categorie trattano i dati personali medesimi in qualità di autonomi titolari del trattamento, ovvero in qualità di responsabili del trattamento, con riferimento a specifiche operazioni di trattamento che rientrano nelle prestazioni contrattuali che i soggetti medesimi eseguono a favore/nell’interesse del titolare del trattamento; ai responsabili del trattamento il titolare del trattamento impartisce adeguate istruzioni operative scritte, con particolare riferimento all’adozione delle misure minime di sicurezza, al fine di poter garantire la riservatezza e la sicurezza dei dati.</p>
            <p>Alcune operazioni di trattamento possono essere effettuate da soggetti terzi, ai quali il titolare del trattamento affida talune attività, o parte di esse, anche funzionalmente alle finalità di cui al punto (4b), tra cui meritano menzione, a titolo comunque, inevitabilmente, non esaustivo: partners commerciali e/o tecnici; società che prestano istituzionalmente servizi di marketing; agenzie pubblicitarie; soggetti che prestano attività di assistenza e consulenza con riferimento a concorsi e operazioni a premio. I soggetti appartenenti alle predette categorie trattano i dati personali in qualità di autonomi titolari del trattamento, ovvero in qualità di responsabili del trattamento, con riferimento a specifiche operazioni di trattamento che rientrano nelle prestazioni contrattuali che i soggetti medesimi eseguono a favore/nell’interesse del titolare del trattamento; ai responsabili del trattamento il titolare del trattamento impartisce adeguate istruzioni operative scritte, con particolare riferimento all’adozione delle misure minime di sicurezza, al fine di poter garantire la riservatezza e la sicurezza dei dati.</p>
            <p>È disponibile, previa richiesta scritta da inviarsi presso la sede del titolare del trattamento, l’elenco, soggetto ad aggiornamento periodico, dei responsabili del trattamento con cui il titolare del trattamento stesso intrattiene rapporti.</p>
            <p>I dati personali possono, inoltre, essere comunicati, in caso di richiesta, alle autorità competenti, in adempimento di obblighi derivanti da norme inderogabili di legge.</p>
        <h4>(8b) Trasferimento dei dati personali verso Paesi terzi</h4>
            <p>I dati personali del Cliente/interessato possono anche essere trasferiti all’estero, sia in Paesi dell’Unione Europea che in Paesi al di fuori dell’Unione Europea e, in quest’ultimo caso, o sulla base di una decisione di adeguatezza, o nell’ambito e con le garanzie adeguate previste dal GDPR (dunque, in particolare, in presenza di clausole contrattuali tipo di protezione dei dati approvate dalla Commissione Europea), o, al di fuori delle ipotesi sopra richiamate, ricorrendo una o più delle deroghe previste dal GDPR (in particolare, in forza di esplicito consenso del Cliente/interessato, o per l’esecuzione del Contratto concluso dal Cliente/interessato, ovvero per l’esecuzione di un contratto stipulato tra il titolare del trattamento e un’altra persona fisica o giuridica a favore del Cliente/interessato, segnatamente per l’esecuzione di attività a questa demandate dal titolare del trattamento medesimo per l’esecuzione del Contratto concluso con il Cliente/interessato). Per l’ipotesi di trasferimenti di dati verso Paesi al di fuori dell’Unione Europea, al Cliente/interessato è consentito, previa richiesta scritta da inviarsi presso la sede del titolare del trattamento, di conoscere le garanzie adeguate, ovvero le deroghe, che legittimano il trattamento transfrontaliero. Resta inteso, in ipotesi di trasferimento dei dati verso Paesi al di fuori dell’Unione Europea, che per ogni richiesta inerente i dati, anche per l’esercizio dei diritti riconosciuti dal GDPR al Cliente/interessato, questo potrà sempre validamente rivolgersi al titolare del trattamento.</p>
        <h3>9. CRITERI PER DETERMINARE IL PERIODO DI CONSERVAZIONE DEI DATI PERSONALI</h3>
            <p>Per le finalità di cui al punto (4a) che precede, il periodo di conservazione dei dati personali rilasciati dal Cliente/interessato, ed il conseguente loro potenziale trattamento, coincide con il periodo di prescrizione dei diritti/doveri (legali, fiscali, ecc.) discendenti dal Contratto: tendenzialmente 10 anni, quindi, salvo il verificarsi di eventi interruttivi della prescrizione che potrebbero prolungare, di fatto, detto periodo.</p>
            <p>Per le finalità di cui al punto (4b) che precede, il periodo di conservazione dei dati rilasciati dal Cliente/interessato, ed il conseguente loro potenziale trattamento, termina con la revoca del consenso preventivamente rilasciato dal Cliente/interessato stesso o, in mancanza di questa, comunque decorso un anno dalla cessazione di ogni rapporto tra il titolare del trattamento ed il Cliente/interessato.</p>
        <h3>10. DIRITTI DEL CLIENTE/INTERESSATO</h3>
            <p>Il titolare del trattamento riconosce – ed agevola l’esercizio, da parte del Cliente/interessato, di – tutti i diritti previsti dal GDPR, in particolare il diritto di chiedere l’accesso ai propri dati personali e di estrarne copia (art. 15 GDPR), alla rettifica (art. 16 GDPR) ed alla cancellazione degli stessi (art. 17 GDPR), alla limitazione del trattamento che lo riguardi (art. 18 GDPR), alla portabilità dei dati (art. 20 GDPR, ove ne ricorrano i presupposti) e di opporsi al trattamento che lo riguardi (artt. 21 e 22 GDPR, per le ipotesi ivi menzionate e, in particolare, al trattamento per finalità di marketing o che si traduca in un processo decisionale automatizzato, compresa la profilazione, che produca effetti giuridici che lo riguardano, ove ne ricorrano i presupposti).</p>
            <p>Il titolare del trattamento riconosce, altresì, al Cliente/interessato, qualora il trattamento sia basato sul consenso, il diritto di revocare detto consenso in qualsiasi momento, senza pregiudicare la liceità del trattamento basata sul consenso prestato prima della revoca. Per fare ciò, il Cliente/interessato può disiscriversi in ogni momento sul Sito (o su altre applicazioni social o web del titolare del trattamento) o utilizzando l’apposito link presente in calce ad ogni comunicazione commerciale ricevuta, oppure contattando il titolare del trattamento ai recapiti sopra riportati.</p>
            <p>Il titolare del trattamento informa, inoltre, il Cliente/interessato del diritto di proporre reclamo all’Autorità Garante per la Protezione dei Dati Personali, quale autorità di controllo operante in Italia, e di proporre ricorso giurisdizionale, tanto avverso una decisione dell’Autorità Garante, quanto nei confronti del titolare del trattamento stesso e/o di un responsabile del trattamento.</p>
            <p>Il Cliente/interessato, nel caso voglia modificare o cancellare i dati che ha conferito tramite il sito, può fare richiesta direttamente al titolare. Nel caso in cui il cliente/interessato si sia registrato all’interno del sito, può utilizzare la sua area riservata per esercitare tutti i diritti previsti dall’informativa.</p>
            <p>Nel caso di richiesta di cancellazione dei suoi dati, La informiamo che potrebbe non essere più possibile continuare a fornirLe il servizio richiestoci.</p>
        <h3>11. SICUREZZA DEI SISTEMI E DEI DATI PERSONALI</h3>
            <p>Tenendo conto dello stato dell’arte e dei costi di attuazione, nonché della natura, dell’oggetto, del contesto e delle finalità del trattamento, come anche del rischio, in termini di probabilità e gravità, per i diritti e le libertà delle persone fisiche, il titolare del trattamento adotta misure tecniche ed organizzative ritenute appropriate a garantire un livello di sicurezza adeguato al rischio, in particolare assicurando, su base permanente, la riservatezza, l’integrità, la disponibilità e la resilienza dei sistemi e dei servizi di trattamento (anche attraverso la cifratura dei dati personali, ove necessario) e la capacità di ripristinare tempestivamente la disponibilità dei dati in caso di incidente fisico o tecnico, ed adottando procedure interne dirette a testare, verificare e valutare regolarmente l’efficacia delle misure tecniche e organizzative impiegate.</p>
            <p>Nel valutare l’adeguato livello di sicurezza, si tiene conto dei rischi presentati dal trattamento che derivano, in particolare, dalla distruzione, dalla perdita, dalla modifica, dalla divulgazione non autorizzata o dall’accesso, in modo accidentale o illegale, a dati personali trasmessi, conservati o comunque trattati.</p>
            <p>Il titolare del trattamento si adopera affinché chiunque agisca sotto la propria autorità ed abbia accesso a dati personali non tratti tali dati se non è istruito in tal senso dal medesimo titolare del trattamento.</p>
            <p>Ciò detto, il Cliente/interessato prende atto ed accetta che nessun sistema di sicurezza garantisce, in termini di certezza, la protezione assoluta; pertanto, il titolare del trattamento non risponde per atti o fatti di terzi che abusivamente, nonostante le adeguate cautele adottate, dovessero accedere ai sistemi senza le dovute autorizzazioni.</p>
        <h3>12. PROCESSI DECISIONALI AUTOMATIZZATI, COMPRESA LA PROFILAZIONE</h3>
            <p>Il titolare del trattamento può effettuare trattamenti automatizzati, compresa la profilazione, in relazione alle finalità di cui al punto (4b) che precede, per ottimizzare la navigabilità del Sito (o la fruibilità di altre applicazioni social o web del titolare del trattamento) e per migliorare l’esperienza d’acquisto, salvo quanto sopra specificato con riguardo ai diritti di opposizione e revoca del consenso da parte del Cliente/interessato.</p>
            <p>Per profilazione s’intende qualsiasi forma di trattamento automatizzato di dati personali diretto a valutare determinati aspetti relativi a una persona fisica, in particolare per analizzare o prevedere aspetti riguardanti, ad esempio, le preferenze personali, gli interessi o l’ubicazione di detta persona, anche al fine di creare profili, ovvero gruppi omogenei di soggetti per caratteristiche, interessi o comportamenti.</p>
            <p>Il titolare del trattamento non effettua alcun trattamento automatizzato che produca effetti giuridici che riguardano il Cliente/interessato o che incidano in modo analogo significativamente sulla sua persona, salvo che ciò sia necessario per la conclusione o l’esecuzione del Contratto, sia autorizzato dalla legge o si basi sul consenso esplicito del Cliente/interessato, in ogni caso sempre riconoscendo a quest’ultimo il diritto di ottenere l’intervento umano, di esprimere la propria opinione e di contestare la decisione.
            </p>
    </section>
 
        `
    }
}
